import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div data-theme="silk">
          <div className="navbar bg-base-100 shadow-sm">
            <a className="btn btn-ghost text-xl">PhotoOps</a>
          </div>
          <div className="grid place-content-center border-t border-base-300 h-[calc(100vh-64px)]">
            {children}
          </div>
        </div>
      </body>
    </html>
  );
}
